version: '3'

services:
  frontend:
    build:
      context: frontend
      dockerfile: Dockerfile
    restart: always
    container_name: frontend
    ports: 
      - "3000:3000"

  api:
    build:
      context: api
      dockerfile: Dockerfile
    container_name: api
    network_mode: "host"
    restart: always
    command: python3 app.py
    working_dir: /app